"""
output/trace.py

Immutable data structures for the transparent reasoning trace.

A ReasoningTrace is a complete, auditable record of every computation step
that produced one RoutingDecision. It is the evidentiary foundation for the
`reason` field in the output CSV.

Design principle — FAITHFULNESS:

  Every field in ReasoningTrace maps 1:1 to a computation result that
  actually occurred. The trace cannot claim:
    - a state was assigned without reading InferredMessageState
    - a policy fired without the policy engine returning that policy_id
    - dissenting evidence existed without it being present in EvidenceBundle
    - a historical message influenced the decision without being in
      HistoricalMatchEvidence.evidence_ids

  This is in contrast to post-hoc LLM explanation, which could rationalize
  any decision with any reason. The TraceBuilder (trace_builder.py) enforces
  faithfulness by construction — it only reads, never invents.

  Consequence: the `reason` string is generated from named templates keyed
  on the actual policy_id, augmented with the actual inference trace string.
  Changing the policy that fires automatically changes the reason.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from inference.states import GuardFired
from policy.models import PolicyDecision


# ---------------------------------------------------------------------------
# Atomic trace steps
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class EvidenceStep:
    """
    One named evidence observation from one pipeline.

    `supports_action` is a coarse annotation — it is set by the TraceBuilder
    based on the field's actual value, not inferred from the decision.
    """

    pipeline: str           # e.g. "ScamRiskPipeline"
    field: str              # e.g. "risk_level"
    value: str              # e.g. "medium"
    interpretation: str     # e.g. "Domain age 9d with mismatch — phishing risk"
    supports_action: str    # "mute" | "notify" | "digest" | "neutral"


@dataclass(frozen=True)
class InferenceStep:
    """
    One state derivation from evidence.
    """
    state_name: str          # e.g. "ContentRiskState"
    state_value: str         # e.g. "PHISHING"
    guard: GuardFired        # the priority guard that matched
    evidence_inputs: tuple[str, ...]   # e.g. ("ScamRiskEvidence.risk_level",)





@dataclass(frozen=True)
class DissentStep:
    """
    Evidence that pointed in the OPPOSITE direction from the taken action.

    Dissenting evidence is real — it exists in the EvidenceBundle. Including
    it makes the trace honest about what was considered and overruled.

    `overrule_reason` explains which policy principle caused the dissent to
    be outweighed. It is keyed on the action + the evidence type, not
    generated by an LLM.
    """

    source: str           # e.g. "HistoricalMatchPipeline"
    field: str            # e.g. "pattern_label"
    value: str            # e.g. "trusted_sender"
    argues_for: str       # what action this evidence would suggest
    overrule_reason: str  # why it was overruled despite existing


# ---------------------------------------------------------------------------
# Full reasoning trace — the complete audit record for one message
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ReasoningTrace:
    """
    Complete, immutable record of every computation step that produced
    one RoutingDecision.

    Built by TraceBuilder after the inference engine and policy engine
    complete. Consumed by:
      - PolicyEngine: extracts `reason` string → writes to RoutingDecision
      - Orchestrator: optionally logs to_debug_report() for audit/debugging
      - Tests: verifies trace faithfulness assertions

    Tuples are used instead of lists so the dataclass can be frozen.
    """

    message_id: str

    # ── five-part chain ───────────────────────────────────────────────────
    evidence_chain:       tuple[EvidenceStep, ...]
    inference_chain:      tuple[InferenceStep, ...]
    policy_decision:      PolicyDecision
    dissenting_evidence:  tuple[DissentStep, ...]
    evidence_message_ids: tuple[str, ...]   # from HistoricalMatchEvidence

    # ── final decision (mirrors RoutingDecision for cross-checking) ───────
    action:       str
    message_type: str
    confidence:   float
    reason:       str   # from PolicyDecision.explanation

    # ── audit helpers ─────────────────────────────────────────────────────

    def to_debug_report(self) -> str:
        """
        Multi-line audit trail. Not written to CSV. Used for debugging,
        manual review, and evaluation of the system's reasoning quality.

        Format is stable — downstream tooling may parse it.
        """
        lines: list[str] = []
        sep = "─" * 60

        lines.append(f"=== REASONING TRACE: {self.message_id} ===")
        lines.append("")
        lines.append(
            f"DECISION: {self.action.upper()} | {self.message_type}"
            f" | confidence={self.confidence:.2f}"
        )
        lines.append("")

        # Evidence chain
        lines.append("EVIDENCE CHAIN:")
        for step in self.evidence_chain:
            lines.append(
                f"  [{step.pipeline:<28s}] {step.field}={step.value!r:<30s}"
                f" → {step.supports_action}"
            )
            if step.interpretation:
                lines.append(f"      {step.interpretation}")
        lines.append("")

        # Inference chain
        lines.append("INFERENCE CHAIN:")
        for step in self.inference_chain:
            lines.append(f"  {step.state_name:<22s} = {step.state_value}")
            lines.append(f"    guard  : {step.guard.name}")
            lines.append(f"    details: {step.guard.details}")
            lines.append(f"    inputs : {', '.join(step.evidence_inputs)}")
        lines.append("")

        # Policy fired
        pd = self.policy_decision
        lines.append(f"POLICY FIRED: {pd.policy_name}")
        lines.append(f"  priority: {pd.priority}")
        lines.append(f"  evidence: {', '.join(pd.evidence_used)}")
        lines.append("")

        # Dissenting evidence
        if self.dissenting_evidence:
            lines.append("DISSENTING EVIDENCE:")
            for d in self.dissenting_evidence:
                lines.append(
                    f"  [{d.source}] {d.field}={d.value!r}"
                    f" argues for {d.argues_for.upper()}"
                )
                lines.append(f"    overruled: {d.overrule_reason}")
        else:
            lines.append("DISSENTING EVIDENCE: none")
        lines.append("")

        # Evidence IDs
        ids_str = "; ".join(self.evidence_message_ids) if self.evidence_message_ids else "none"
        lines.append(f"EVIDENCE IDs: {ids_str}")
        lines.append("")

        lines.append(f"REASON: {self.reason}")
        lines.append("=" * 60)

        return "\n".join(lines)
